/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// =====================================| Project Factory |=====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------------
		
		registerPolyNode<project::JpRevTest<1>, project::JpRevTest<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::JPVERBTEST<1>, project::JPVERBTEST<NUM_POLYPHONIC_VOICES>>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

